# Generated by Django 6.0.3 on 2026-03-25 18:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('item_type', models.CharField(choices=[('GOODS', 'Goods'), ('SERVICE', 'Service')], default='GOODS', max_length=10)),
                ('unit', models.CharField(default='Nos', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/images/%Y/%m/')),
                ('hsn_code', models.CharField(blank=True, help_text='6-digit HSN code (Goods) or SAC code (Services)', max_length=6, null=True, validators=[django.core.validators.RegexValidator(message='HSN/SAC code must be exactly 6 numeric digits (e.g., 010101).', regex='^\\d{6}$')])),
                ('tax_preference', models.CharField(choices=[('TAXABLE', 'Taxable'), ('NON_TAXABLE', 'Non-Taxable'), ('EXEMPT', 'Exempt'), ('OUT_OF_SCOPE', 'Out of Scope')], default='TAXABLE', max_length=20)),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('selling_account', models.CharField(choices=[('SALES', 'Sales'), ('SALES_RETURN', 'Sales Return'), ('GENERAL_INCOME', 'General Income'), ('INTEREST_INCOME', 'Interest Income'), ('OTHER_INCOME', 'Other Income'), ('SHIPPING_INCOME', 'Shipping Income')], default='SALES', max_length=30)),
                ('selling_description', models.TextField(blank=True, default='')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('purchase_account', models.CharField(choices=[('COST_OF_GOODS_SOLD', 'Cost of Goods Sold'), ('PURCHASES', 'Purchases'), ('PURCHASE_RETURN', 'Purchase Return'), ('FREIGHT', 'Freight'), ('OTHER_EXPENSE', 'Other Expense')], default='COST_OF_GOODS_SOLD', max_length=30)),
                ('purchase_description', models.TextField(blank=True, default='')),
                ('intra_state_tax_rate', models.DecimalField(blank=True, decimal_places=2, help_text='CGST + SGST rate for intra-state supply (%)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('inter_state_tax_rate', models.DecimalField(blank=True, decimal_places=2, help_text='IGST rate for inter-state supply (%)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'items',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['item_type', 'is_active'], name='items_item_ty_b34ed6_idx'), models.Index(fields=['hsn_code'], name='items_hsn_cod_501cf6_idx'), models.Index(fields=['tax_preference'], name='items_tax_pre_683259_idx')],
            },
        ),
    ]
