# Generated by Django 6.0.3 on 2026-03-27 19:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='uid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
