# Generated by Django 6.0.3 on 2026-03-29 14:26

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_item_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='inventory_account',
            field=models.CharField(blank=True, choices=[('INVENTORY', 'Inventory Asset'), ('RAW_MATERIALS', 'Raw Materials'), ('WORK_IN_PROGRESS', 'Work in Progress'), ('FINISHED_GOODS', 'Finished Goods')], help_text='Account head for inventory asset. Required when track_inventory is True.', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='inventory_valuation_method',
            field=models.CharField(blank=True, choices=[('FIFO', 'FIFO (First-In-First-Out)'), ('LIFO', 'LIFO (Last-In-First-Out)'), ('WEIGHTED_AVERAGE', 'Weighted Average')], help_text='Method used to value inventory. Required when track_inventory is True.', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='item_description',
            field=models.TextField(blank=True, default='', help_text='Detailed description of the item.'),
        ),
        migrations.AddField(
            model_name='item',
            name='reorder_point',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum stock level that triggers a reorder (in base unit).', null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='sku',
            field=models.CharField(blank=True, help_text='Stock Keeping Unit – unique identifier for the item.', max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='SKU must be alphanumeric and up to 12 characters (no symbols).', regex='^[A-Za-z0-9]{1,12}$')]),
        ),
        migrations.AddField(
            model_name='item',
            name='track_inventory',
            field=models.BooleanField(default=False, help_text='Enable inventory tracking for this item.'),
        ),
        migrations.AlterField(
            model_name='item',
            name='uid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier used in API endpoints.', unique=True),
        ),
    ]
